# Generated by Django 2.2.7 on 2019-11-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_site_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
